#http
services:
  app:
    image: ghcr.io/mahn-ke/rcon-by-vincent:latest@sha256:7bf68d621136fa084b0450ae82f7b4da5439037211da9560c5fbcf040d69a676
    restart: on-failure:5
    environment:
      - RCON_SERVER=${RCON_SERVER}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - ALLOWLIST_SECRET=${ALLOWLIST_SECRET}
      - PORT=3000
    ports:
      - "3016:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
