#http
services:
  app:
    image: ghcr.io/mahn-ke/rcon-by-vincent:latest@sha256:9650d62fd110465871f98d049d28879d9d7585fd9ebb2a0932083695470f083d
    restart: on-failure:5
    environment:
      - RCON_SERVER=${RCON_SERVER}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - ALLOWLIST_SECRET=${ALLOWLIST_SECRET}
      - PORT=3000
    ports:
      - "3016:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
