#http
services:
  app:
    image: ghcr.io/mahn-ke/rcon-by-vincent:latest@sha256:2c25c9584cd3f1038fca3728e158a227611b7624755552d75b48f4e844cbd2a7
    restart: on-failure:5
    environment:
      - RCON_SERVER=${RCON_SERVER}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - ALLOWLIST_SECRET=${ALLOWLIST_SECRET}
      - PORT=3000
    ports:
      - "3016:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
